services:
  postgres:
    image: postgres:17-alpine
    container_name: munshi-dev-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: munshi-admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: munshi-db
    ports:
      - "5432:5432"
    volumes:
      - munshi-data:/var/lib/postgresql/data

  redis:
    image: redis:8.4-alpine
    container_name: munshi-dev-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    # Optional: Command to ensure data is saved to disk regularly
    command: redis-server --save 60 1 --loglevel warning
  
  redis-insight:
    image: redis/redisinsight:latest
    container_name: munshi-dev-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redis-insight-data:/data

volumes:
  munshi-data:
  redis-data:
  redis-insight-data: